variables:
  - name: BuildParameters.RESTOREBUILDPROJECTS
    value: "**/*.csproj"
  - name: BUILDCONFIGURATION
    value: Release
name: "custom-transformer-example"
jobs:
  - job: Job_1
    displayName: Agent job 1
    pool: "mechamachine"
    steps:
      - checkout: self
      - task: NodeTool@0
        displayName: Use Node 10.16.3
        inputs:
          versionSpec: 10.16.3
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: "$(BuildParameters.RESTOREBUILDPROJECTS)"  
     - task: SSISCatalog@0
       displayName: Configure SSIS Catalog
       inputs:
         configPath: azure-pipelines-1.yml
         targetServer: foo
         authType: win
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: "$(BuildParameters.RESTOREBUILDPROJECTS)"
          arguments: "--configuration $(BUILDCONFIGURATION)"
